### ISSUE TITLE
Data class for (de)serialization

### ISSUE THREAD

**Issue by aladuca** [ajryan/RptToXml#14]
I would like to see this project use a data class for serialization of Crystal Reports objects that are documented. This would allow other applications to easily import the XML into an object for conversion/analysis without needing Crystal Reports libraries. 

I have already started the process, but I wanted to see if it interested you. (It also adds the ability to easily export to JSON)

**References:**
Object to XML: http://support.microsoft.com/kb/815813
Object to JSON: https://msdn.microsoft.com/en-us/library/bb412179%28v=vs.110%29.aspx

**Comment by ajryan** [comment]
Hi, this is an interesting idea. Do you have a specific use case in mind?
That could help with designing the API / data structure.

**Comment by aladuca** [comment]
I want to use it to convert the data into a database (mainly for table look-ups) / extend my web interface to show tables and links for reports. For the most part I am trying to model the data structure after your current one. I got as far as Area's which I am still working on.

Data Model (so far): https://github.com/aladuca/RptToXml/blob/master/RptToXml/RptDefinition.cs
Web Interface: https://github.com/aladuca/RptPutty

**Comment by ajryan** [comment]
I think a lot of people could find this useful. There's one big caveat - we need to maintain backward compatibility with existing XML files, because a lot of people use this tool to check for differences between versions of a report. An identical report must produce identical XML in current and future versions of this tool.

You may be better off just working with the XML and XPath...

**Comment by slestak** [comment]
How would this reduce the need for the CR SDK?  It seems they would still be a dependency.

**Comment by ajryan** [comment]
We would still need to use the CR SDK to produce the output, but other people could write code that deserializes the XML into @aladuca 's data model and inspect the report without needing the SDK.

**Comment by slestak** [comment]
Regarding backwards compatibility of the xml, I have added to my workflow when creating a branch for an issue, regenerating my xml dump for the reports in question before my work to accommodate changes to RptToXML.  As long as it creates the same xml for each run we should be ok, but we shouldn't stop adding features and fixing bugs.

**Comment by aladuca** [comment]
@ajryan is correct with his use case. I use a limited data model for my RptPutty project that is used for UI presentation of parameters and their values, but it is generated every time (~2+ seconds wait time) vs loading it from a database after comparison of SHA1 sums of the Crystal Report (milliseconds).

@slestak I did think about how to keep the legacy model and it just came to me recently. The process I propose is to directly place the values into the data model then have a separate class that converts the data model to the legacy xml format.

**Comment by ajryan** [comment]
Steve, completely agree - no need to freeze bugfixes or features. This particular enhancement would fundamentally change the way the output is produced so it has a much higher risk of introducing compatibility issues.

**Comment by ajryan** [comment]
Closing stale issue.
