### ISSUE TITLE
Format field formulas not serialized 

### ISSUE THREAD

**Issue by dcembala** [ajryan/RptToXml#21]
![image](https://cloud.githubusercontent.com/assets/13776914/9403935/71a34716-47eb-11e5-9981-262dd95bf4ff.png)

Font formating formulas seems to be skiped when generating xml, no difference before and after change any of them.

**Comment by slestak** [comment]
AJ, I am tied up with project work so I will not be able to get to this anytime soon.

**Comment by ajryan** [comment]
I'm also pretty busy right now. If anyone out there has time to look into this, please take a shot and send a PR.

**Comment by dcembala** [comment]
Also report custom functions are not serialized.

**Comment by slestak** [comment]
decembela, can you provide an example (in a new issue please) for the report custom function.  I will be sending a pull request shortly for the FontColorCOnditionFormulas detail.

**Comment by slestak** [comment]
#25 pull request

**Comment by dcembala** [comment]
Custom functions added as #26
