### ISSUE TITLE
Unable to get Chart Type and Assigned Data Details

### ISSUE THREAD

**Issue by anubankar** [ajryan/RptToXml#22]
I converted RPT files to XML. But I am unable to get Chart Type and the data assigned to the Chart. 
What I need for every chart is:
Chart Type : Bar / Chart / Pie etc
X Axis: Field Name
Y Axis: Field Name

Appreciate your help on this one.

**Comment by ajryan** [comment]
Hi, sorry I  missed this issue a long time ago. If anyone has a sample report with a chart that we can work with, we can reopen.
