### ISSUE TITLE
Custom functions not serialized

### ISSUE THREAD

**Issue by dcembala** [ajryan/RptToXml#26]
![custom_functions](https://cloud.githubusercontent.com/assets/13776914/14416870/4a1084bc-ffaf-11e5-83ec-50fd38098fe5.png)

Custom functions in report and subreports are not serialized.

**Comment by slestak** [comment]
AJ,

I have a branch with this working for the main report, however, not for subreports.

Tried a few things, but nothing so far is successful.  Work is picking up so I will push what I have.  Maybe you can see what I was missing?  In my branch I will include a sample report that has a single subreport and both main and sub each have a custom function.

Steve

**Comment by ajryan** [comment]
Hi Steve, thanks for pushing this forward and thanks for the sample report. I may have some time to take a look later this month, will update if/when I do.

**Comment by slestak** [comment]
What do you think about adding the sample report i have as a unit test?  Do you have a preference on a testing framework if I was to do that on my branch?

**Comment by ajryan** [comment]
Closing stale issue. If anyone has a current need or fix ready, we can reopen.
