### ISSUE TITLE
Load report failed. A document processed by the JRC engine cannot be opened in the C++ stack.

### ISSUE THREAD

**Issue by sunk818** [ajryan/RptToXml#28]
I'm getting this error if the file is already opened by another program it seems.

```
Dumping C:\temp\crystal.rpt

Unhandled Exception: CrystalDecisions.Shared.CrystalReportsException: Load report failed. ---> System.Runtime.InteropServices.COMException: Unsupported Operation. A document processed by the JRC engine cannot be opened in the C++ stack.
   at CrystalDecisions.ReportAppServer.ClientDoc.ReportClientDocumentClass.Open(Object& DocumentPath, Int32 Options)
   at CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper.Open(Object& DocumentPath, Int32 Options)
   at CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper.EnsureDocumentIsOpened()
   --- End of inner exception stack trace ---
   at CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper.EnsureDocumentIsOpened()
   at CrystalDecisions.CrystalReports.Engine.ReportDocument.Load(String filename, OpenReportMethod openMethod, Int16 parentJob)
   at CrystalDecisions.CrystalReports.Engine.ReportDocument.Load(String filename, OpenReportMethod openMethod)
   at RptToXml.RptDefinitionWriter..ctor(String filename) in c:\Development\RptToXml\RptToXml\RptDefinitionWriter.cs:line 35
   at RptToXml.Program.Main(String[] args) in c:\Development\RptToXml\RptToXml\Program.cs:line 57
```

**Comment by ajryan** [comment]
This appears to be as simple as the report not existing at the path you've passed to the tool.

http://stackoverflow.com/questions/10833894/a-document-processed-by-the-jrc-engine-cannot-be-opened-in-the-c-stack

**Comment by sunk818** [comment]
the report exists. it is just opened by crystal report (in use?) desktop. when the file is in use, the rpttoxml tool seems to not be able to process the .rpt file

**Comment by ajryan** [comment]
Could you please email me a copy of the report to the address listed in my GitHub profile? Thanks.

**Comment by sunk818** [comment]
The issue has to do with RptToXml trying to process a .rpt file that is already opened by Crystal Reports. It is not a specific report... you can try it yourself on your end without using one of my reports to replicate the issue.

**Comment by ajryan** [comment]
Sorry I misread your comment "just opened by crystal report" to mean the report opened OK in Crystal Reports. Now I understand it doesn't work if the file is already open.

I doubt there is a way to process an RPT file that is already open in Crystal Reports. Were you expecting this to work? Or just to receive a better error message?

**Comment by sunk818** [comment]
> Were you expecting this to work? Or just to receive a better error message?

I wanted better error handling.

**Comment by ajryan** [comment]
In the future it would be useful to describe the expected behavior when you submit an issue, maintainers will have an easier time helping you.

It looks like it just throws a generic `CrystalReportsException`. I don't believe there is any way for our code to tell the difference between the report being already open versus some other issue (corrupt file for example). We can include some generic text when this exception occurs similar to "Report could not be opened. Please ensure the file is not open in Crystal Reports." This will be a red herring for some users but seems like it would be helpful enough that I'm OK with adding it.
