### ISSUE TITLE
Creation of Group Header not exported to XML

### ISSUE THREAD

**Issue by sunk818** [ajryan/RptToXml#29]
When I re-export from RPT To XML, creating a Group Header is not being shown in the XML.

**Comment by ajryan** [comment]
Do any group headers appear, or only newly-created ones?

**Comment by sunk818** [comment]
No group headers appear in the XML.

**Comment by ajryan** [comment]
Could you please attach a sample report we can use for testing?

**Comment by ajryan** [comment]
Closing with no response. If you can provide a sample I'll reopen.
