### ISSUE TITLE
Method 'get_HistoryInfos' in type does not have an implementation.

### ISSUE THREAD

**Issue by leonel7** [ajryan/RptToXml#33]
Added all updated .NET libraries, installed the run times, the code compiles but fails one of the library calls. spent almost a full day trying to get this to work it just  ** does not work ** : 
An unhandled exception of type 'System.TypeLoadException' occurred in CrystalDecisions.CrystalReports.Engine.dll
Additional information: Method 'get_HistoryInfos' in type 'CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper' from assembly 'CrystalDecisions.CrystalReports.Engine, Version=13.0.2000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304' does not have an implementation.

**Comment by leonel7** [comment]
Tried both the old (original) libraries and updated libraries, Tried forums's suggestions to set 'Embed Interop Types' to False for all libraries - same issue.

**Comment by ajryan** [comment]
This kind of smells like there could be conflicting versions of some references available, maybe in the GAC? Do you have any other versions of Crystal installed on this system?

**Comment by leonel7** [comment]
@ajryan, thanks for the reply.  I ditched this tool and instead I installed Crystal Reports XI Release 2 v.11.5 so that I could extract the SQL query from a crystal report.  Good luck on your en-devours.
