### ISSUE TITLE
CrystalDecisions can be imported as NuGet packages

### ISSUE THREAD

**Issue by ascire** [ajryan/RptToXml#34]
Hey, I was just revisiting this and I noticed that there's a missed opportunity to import CrystalDecisions packages from NuGet.

Mind if I take a crack at this?

**Comment by ajryan** [comment]
Totally!

**Comment by ascire** [comment]
There are DLLs in NuGet, but they are either stubs or are otherwise useless without installing the Crystal runtime anyway.

Using the NuGet packages grants you the ability to build without having the Crystal runtime installed, such as on a build server, but you can't run the application without the runtime.

I may re-open the above referenced pull request once I've done a little testing.

**Comment by ajryan** [comment]
I just switched to the NuGet packages which at least let me build a release. I think it's a win!
