### ISSUE TITLE
Q:  Is it possible to reverse the process?

### ISSUE THREAD

**Issue by tforsberg** [ajryan/RptToXml#36]
In other words, is it possible to create the RPT file from the XML?

**Comment by ajryan** [comment]
Nope

**Comment by tforsberg** [comment]
Ok.  I understand your project does not do this, but do think that it is technically possible to do?

**Comment by ajryan** [comment]
I'm not sure if it's possible to programmatically define every single report object. Also, this tool does not capture everything, so if you started from the XML produced by this tool you would be missing some objects/properties.

However, for simpler reports, you may be successful in reversing to XML to an RPT.

What is your specific use case?

**Comment by tforsberg** [comment]
I have several reports that are used by different clients (on different databases, but same schema).  I would like to be able to change the data source and regenerate the report for a specific client.

**Comment by ajryan** [comment]
There's no need to serialize/deserialize into/out of XML for that. You can modify a report in memory at runtime to change the data sources. Something like the following should work. This post may be a bit out of date versus the current API, but you get the idea: https://www.codeproject.com/Articles/270977/Change-the-data-source-of-a-Crystal-Report-at-Run
