### ISSUE TITLE
getting error : The document has not been opened.

### ISSUE THREAD

**Issue by np0316** [ajryan/RptToXml#38]
I am getting this error while running it from VS 2013 or from command line. Can someone please help?

An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in CrystalDecisions.CrystalReports.Engine.dll

Additional information: The document has not been opened.

**Comment by ajryan** [comment]
It would help if you can provide a full stack trace.

**Comment by sunk818** [comment]
@np0316 try these:

https://social.msdn.microsoft.com/Forums/en-US/07b117a4-5096-4508-b0f9-c6acdec1e9c9/systemruntimeinteropservicescomexception-occurred-in-crystaldecisionscrystalreportsenginedll?forum=vscrystalreports

https://answers.sap.com/questions/4837489/index.html

**Comment by np0316** [comment]
Thank you for your replies. I am not even sure if I am using the program from its intended use. I have several crystal report .rpt files and I just need to extract report definition from them. So I thought converting it into xml will help me read the file and automate it. Other way is opening each rpt file in manually in crystal report and export report definition which I wanted to avoid. Is this tool right tool for me?

**Comment by ajryan** [comment]
Sorry for forgetting about this issue. Why do you need to extract the report definition? What's your ultimate goal?

**Comment by AnitaM02** [comment]
@ajryan I am getting a similar error but have exhausted all ways to fix it .  I am providing the stack trace  kindly point out whats wrong and what can be fixed. Thanks.
[stcaktrace errSystem.Runtime.InteropServices.COMException.txt](https://github.com/ajryan/RptToXml/files/3696892/stcaktrace.errSystem.Runtime.InteropServices.COMException.txt)

**Comment by AnitaM02** [comment]
using crystal report vs 13.0.25.3158 and VS2017 .

**Comment by aidanjryan** [comment]
@AnitaM02 sorry, I'm not able to provide support for this tool.
