### ISSUE TITLE
Order the FormulaFieldDefinition elements by name

### ISSUE THREAD

**Issue by mckuipers** [ajryan/RptToXml#39]
Hi

I was using your excellent utility just now to compare two revisions of a reports. Between these revisions a number of formula's have been added.
But it is very hard to match up, as the order has also changed.
It would be great if the formula extracts could be sorted by name first (before the "foreach (var field in report.DataDefinition.FormulaFields)") so it is much easier to see what formula's have been inserted, amended or deleted.

If you have some sample code, I'm happy to insert and compile/test, but just do not know how to do this myself.

Many thanks in advance and Kind regards
Marco

**Comment by aidanjryan** [comment]
Hi Marco, good idea. This will be easy to change and I don't think anyone is relying on the current behavior. Just curious, what order are formulas displayed in the report editor UI?

**Comment by mckuipers** [comment]
Thanks for your positive response.

The UI shows alphabetic by name

Kind
Regards
Marco
>
IMPORTANT NOTICE: This e-mail message is intended to be received only by persons entitled to receive the confidential information it may contain. E-mail messages to clients of 28 IT Pty Ltd may contain information that is confidential and legally privileged. Please do not read, copy, forward, or store this message unless you are an intended recipient of it. If you have received this message in error, please forward it to the sender and delete it completely from your computer system.

**Comment by ajryan** [comment]
Hi, please try the latest release: https://github.com/ajryan/RptToXml/releases/tag/v1.1.1

**Comment by mckuipers** [comment]
Thanks Aidan

Works perfect!!!

Kind regards
Marco
