### ISSUE TITLE
RptToXml-1.1.2 Binary Error

### ISSUE THREAD

**Issue by emorillo2** [ajryan/RptToXml#44]
Hi, 
I attempted to run RptToXml.exe 1.1.2 binary release I downloaded from here after installing the SAP CR for VS runtime 64bit MSI (SP30) you referenced in the releases area, but had this error:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CrystalDecisions.ReportAppServer.ClientDoc, Version=13.0.4000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304' or one of its dependencies. The system cannot find the file specified.
   at RptToXml.RptDefinitionWriter..ctor(String filename)
   at RptToXml.Program.Main(String[] args) in C:\Users\chris-pickering\Documents\r_source\rpttoxml\RptToXml\Program.cs:line 58
```

I googled it and found similar issue [here](https://stackoverflow.com/questions/38025601/could-not-load-file-or-assembly-crystaldecisions-reportappserver-commlayer-ver) and recommended action was to install 32bit MSI Runtime as well, even though everything else was 64bit. I was able to find the SP30 32bit MSI here: https://origin.softwaredownloads.sap.com/public/site/index.html 

After installing the 32bit SAP CR for VS Runtime, RptToXml ran successfully. Not sure if you need to fix the code or just reference that 32bit Runtime also required.

Not sure if it matters, but I'm running it on a Windows 10 machine; I don't have Visual Studio or Crystal Reports on it.

Thanks so much for this tool!

**Comment by christopherpickering** [comment]
That rings a bell w/ me too. I'm on 64 and pretty sure I needed both. I'm not sure how to fix other than add to the readme to install both? I also don't understand why the paths in the .exe are local paths from the PC I used to build it 😵

**Comment by christopherpickering** [comment]
I've updated the readme. Thanks for mentioning the issue!
