### ISSUE TITLE
I am getting error Missing Method instance class

### ISSUE THREAD

**Issue by Mushi105** [ajryan/RptToXml#56]
An unhandled exception of type 'System.MissingMethodException' occurred in LatesProjectRPTTOXML.exe

Additional information: Error: Missing method 'instance class CrystalDecisions.ReportAppServer.ReportDefModel.ReportDocument [LatesProjectRPTTOXML] CrystalDecisions.ReportAppServer.ClientDoc.ISCDReportClientDocument::get_ReportDocument()' from class 'CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper'.

**Comment by christopherpickering** [comment]
I don't fully understand your problem... Do you mean that the latest update is not working for you?

Have you tried uninstalling the Crystal SP and installing the latest verions that RptToXml is built with? 32 I think?

**Comment by Mushi105** [comment]
Actually i run source code and execution the build than the error occur is

An unhandled exception of type 'System.MissingMethodException' occurred in LatesProjectRPTTOXML.exe

Additional information: Error: Missing method 'instance class CrystalDecisions.ReportAppServer.ReportDefModel.ReportDocument [LatesProjectRPTTOXML] CrystalDecisions.ReportAppServer.ClientDoc.ISCDReportClientDocument::get_ReportDocument()' from class 'CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper'.

**Comment by Mushi105** [comment]
Can you please share the latest link for crystal  sp

**Comment by christopherpickering** [comment]
https://www.sap.com/cmp/td/sap-crystal-reports-visual-studio-trial.html

**Comment by Mushi105** [comment]
Many Many thank your support issue has been revolved by latest version of crystal report sp

**Comment by Mushi105** [comment]
Could you please tell me Crystal Report have been convert rpt to xml
But  I want to show design report rpt to xml in birt report tools

**Comment by christopherpickering** [comment]
Great! No problem.
I don't understand what you want to do? You want to add a button in the Report Designer program with a link to RtpToXml so you can convert reports from the designer?

I'm not sure if that is possible..

**Comment by Mushi105** [comment]
My question is now rpt has been generated in XML File after that i want to use xml file in Birt reporting tool
this is possible

**Comment by ajryan** [comment]
I doubt this tool does what you need here. This tool converts RPT to a consistent XML text format that is useful for diff tools, extracting strings for localization, etc. The XML format from this tool is not used by any other reporting system. I don’t know what BIRT is but it definitely can’t use this format.
