### ISSUE TITLE
Recursive option stopped on the first error

### ISSUE THREAD

**Issue by DamienAuvray** [ajryan/RptToXml#57]
Hi,

Using 1.1.6 version, I was getting an error en few reports with wrong formulas. (maybe same as issue #51 ?).
The problem was that the .exe stopped execution due to the error while dumping the file.

My idea is to add an option to skip errors during the process. I currently have more than hundreds reports and skipping wrong ones would allow me to get the xml for 95% of my reports.

I build this to solve my problem. But It should have a better way to do it :
![image](https://user-images.githubusercontent.com/24833774/202392852-3aa075a7-d7c7-48f9-83db-d9776af4cf07.png)

Result :
![image](https://user-images.githubusercontent.com/24833774/202393444-829661ab-99e8-496f-af55-b28e0f8bedcd.png)

Any idea to add an option that allows the dump to fail ?

**Comment by christopherpickering** [comment]
Its a good idea! how about adding a flag `--ignore-errors`, then if the flag is not set you can reraise inside your catch?

**Comment by DamienAuvray** [comment]
Here is the updated Main code with --ignore-errors args.
It can be use with -r, filename, wildcard and filename+outputfilename. 

```
static void Main(string[] args)
		{
			if (args.Length < 1)
			{
				Console.WriteLine("Usage: RptToXml.exe < -r | RPT filename | wildcard> [outputfilename] [--ignore-errors]");
				Console.WriteLine("       -r : recursively convert all rpt files in current directory and sub directories");
				Console.WriteLine("       outputfilename argument is valid only with single filename in first argument");
				return;
			}
			Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
			string rptPathArg = args[0];
			var rptPaths = new List<string>();
			int ignoreErrFlag = 0;

			if (args.Contains("--ignore-errors"))
				ignoreErrFlag = 1;

			if ("-r".Equals(rptPathArg, StringComparison.InvariantCultureIgnoreCase))
			{
				if (args.Length > 1 + ignoreErrFlag)
				{
					Console.WriteLine("Output filename may not be specified with -r .");
					return;
				}
				recursiveFileList(rptPaths, ".");
			}
			else if (rptPathArg.Contains("*"))
			{
				if (args.Length > 1 + ignoreErrFlag)
				{
					Console.WriteLine("Output filename may not be specified with wildcard.");
					return;
				}
				var directory = Path.GetDirectoryName(rptPathArg);
				if (String.IsNullOrEmpty(directory))
				{
					directory = ".";
				}
				var matchingFiles = Directory.GetFiles(directory, searchPattern: Path.GetFileName(rptPathArg));
				rptPaths.AddRange(matchingFiles.Where(ReportFilenameValid));
				if (rptPaths.Count == 0)
				{
					Trace.WriteLine("No reports matched the wildcard.");
				}
			}
			else
			{
				rptPaths.Add(rptPathArg);
			}
			


			foreach (string rptPath in rptPaths)
			{
				try
				{
					Trace.WriteLine("Dumping " + rptPath);

					using (var writer = new RptDefinitionWriter(rptPath))
					{
						string xmlPath = args.Length > 1 + ignoreErrFlag ?
							args[1] : Path.ChangeExtension(rptPath, "xml");
						writer.WriteToXml(xmlPath);
					}

				} catch(Exception ex)
				{
					if (ignoreErrFlag == 1)
						Trace.WriteLine(ex.Message);
					else
						throw ex;
				}
			}
		}
```

**Comment by christopherpickering** [comment]
nice! Any chance you can make a PR? Thank you!

**Comment by DamienAuvray** [comment]
I tried but got permission denied when I tried to push my branch. Sorry I'm not very used to git.

**Comment by christopherpickering** [comment]
ah no probl, you are trying to push to this repo instead of your fork. I can do a pr tomorrow AM if you'd like.

Otherwise, you can do the editor on github, paste in your code, and it will automatically create a fork.

**Comment by DamienAuvray** [comment]
Thx. I'll try this next time.

**Comment by christopherpickering** [comment]
I will create a new release shortly. Sorry for the delay.

**Comment by ajryan** [comment]
This change should really only apply to the try/catch around converting a report. We shouldn't suppress/ignore the commandline args parsing.
